apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: imac--2048
  namespace: argocd
spec:
  project: imac
  source:
    repoURL: 'https://github.com/amanibhavam/deploy'
    path: imac/2048
    targetRevision: master
  destination:
    name: imac
    namespace: katt-2048
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
