apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: imac--traefik
  namespace: argocd
spec:
  project: imac
  source:
    repoURL: 'https://github.com/amanibhavam/deploy'
    path: imac/traefik
    targetRevision: master
  destination:
    name: imac
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
