apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mini--cilium
  namespace: argocd
spec:
  project: mini
  source:
    repoURL: https://github.com/amanibhavam/deploy
    path: c/mini/cilium
    targetRevision: master
  destination:
    name: mini
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mini--argo-workflows
  namespace: argocd
spec:
  project: mini
  source:
    repoURL: https://github.com/amanibhavam/deploy
    path: c/mini/argo-workflows
    targetRevision: master
  destination:
    name: mini
    namespace: argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mini--docker-registry
  namespace: argocd
spec:
  project: mini
  source:
    repoURL: https://github.com/amanibhavam/deploy
    path: c/mini/docker-registry
    targetRevision: master
  destination:
    name: mini
    namespace: docker-registry
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mini--pihole
  namespace: argocd
spec:
  project: mini
  source:
    repoURL: https://github.com/amanibhavam/deploy
    path: c/mini/pihole
    targetRevision: master
  destination:
    name: mini
    namespace: pihole
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mini--traefik
  namespace: argocd
spec:
  project: mini
  source:
    repoURL: https://github.com/amanibhavam/deploy
    path: c/mini/traefik
    targetRevision: master
  destination:
    name: mini
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mini--kuma-zone
  namespace: argocd
spec:
  project: mini
  source:
    repoURL: https://github.com/amanibhavam/deploy
    path: c/mini/kuma-zone
    targetRevision: master
  destination:
    name: mini
    namespace: kuma-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
