apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: mini
  namespace: argocd
spec:
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  orphanedResources:
    warn: false
    ignore:
    - group: cilium.io
      kind: CiliumIdentity
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: imac
  namespace: argocd
spec:
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  orphanedResources:
    warn: false
    ignore:
    - group: cilium.io
      kind: CiliumIdentity
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: mbpro
  namespace: argocd
spec:
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  orphanedResources:
    warn: false
    ignore:
    - group: cilium.io
      kind: CiliumIdentity
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: immanent
  namespace: argocd
spec:
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  orphanedResources:
    warn: false
    ignore:
    - group: cilium.io
      kind: CiliumIdentity
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: imac--2048
  namespace: argocd
spec:
  project: imac
  source:
    repoURL: https://github.com/amanibhavam/deploy
    path: c/imac/2048
    targetRevision: master
  destination:
    name: imac
    namespace: katt-2048
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: imac--cilium
  namespace: argocd
spec:
  project: imac
  source:
    repoURL: https://github.com/amanibhavam/deploy
    path: c/imac/cilium
    targetRevision: master
  destination:
    name: imac
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: imac--kuma-zone
  namespace: argocd
spec:
  project: imac
  source:
    repoURL: https://github.com/amanibhavam/deploy
    path: c/imac/kuma-zone
    targetRevision: master
  destination:
    name: imac
    namespace: kuma-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: imac--pihole
  namespace: argocd
spec:
  project: imac
  source:
    repoURL: https://github.com/amanibhavam/deploy
    path: c/imac/pihole
    targetRevision: master
  destination:
    name: imac
    namespace: pihole
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: imac--traefik
  namespace: argocd
spec:
  project: imac
  source:
    repoURL: https://github.com/amanibhavam/deploy
    path: c/imac/traefik
    targetRevision: master
  destination:
    name: imac
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

