apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mini--cilium
  namespace: argocd
spec:
  project: mini
  source:
    repoURL: 'https://github.com/amanibhavam/deploy'
    path: mini/cilium
    targetRevision: master
  destination:
    name: mini
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
