apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/letfn/katt-traefik/base?ref=0.0.25
  - ingress.yaml

patches:
  - path: patch-nodeport-http.yaml
    target:
      kind: Service
      name: traefik
  - path: patch-nodeport-https.yaml
    target:
      kind: Service
      name: traefik
  - path: patch-service-cloudflared.yaml
    target:
      kind: Service
      name: traefik
  - path: patch-service-tailscale.yaml
    target:
      kind: Service
      name: traefik
  - path: patch-deployment-volume.yaml
    target:
      kind: Deployment
      name: traefik
  - path: patch-deployment-init.yaml
    target:
      kind: Deployment
      name: traefik
  - path: patch-cluster-issuer.yaml
    target:
      kind: ClusterIssuer
      name: letsencrypt-staging
  - path: patch-cluster-issuer.yaml
    target:
      kind: ClusterIssuer
      name: letsencrypt-prod
  - path: patch-certificate.yaml
    target:
      kind: Certificate
