apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: imac--kuma-zone
  namespace: argocd
spec:
  project: imac
  source:
    repoURL: 'https://github.com/amanibhavam/deploy'
    path: imac/kuma-zone
    targetRevision: master
  destination:
    name: imac
    namespace: kuma-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
