apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: mini
  namespace: argocd
spec:
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  orphanedResources:
    warn: false
    ignore:
    - group: cilium.io
      kind: CiliumIdentity
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: imac
  namespace: argocd
spec:
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  orphanedResources:
    warn: false
    ignore:
    - group: cilium.io
      kind: CiliumIdentity
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: mbpro
  namespace: argocd
spec:
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  orphanedResources:
    warn: false
    ignore:
    - group: cilium.io
      kind: CiliumIdentity
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mini--cilium
  namespace: argocd
spec:
  project: mini
  source:
    repoURL: https://github.com/amanibhavam/deploy
    path: c/mini/cilium
    targetRevision: master
  destination:
    name: mini
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mini--kuma-global
  namespace: argocd
spec:
  project: mini
  source:
    repoURL: https://github.com/amanibhavam/deploy
    path: c/mini/kuma-global
    targetRevision: master
  destination:
    name: mini
    namespace: kuma-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mini--argo-workflows
  namespace: argocd
spec:
  project: mini
  source:
    repoURL: https://github.com/amanibhavam/deploy
    path: c/mini/argo-workflows
    targetRevision: master
  destination:
    name: mini
    namespace: argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mini--docker-registry
  namespace: argocd
spec:
  project: mini
  source:
    repoURL: https://github.com/amanibhavam/deploy
    path: c/mini/docker-registry
    targetRevision: master
  destination:
    name: mini
    namespace: docker-registry
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mini--pihole
  namespace: argocd
spec:
  project: mini
  source:
    repoURL: https://github.com/amanibhavam/deploy
    path: c/mini/pihole
    targetRevision: master
  destination:
    name: mini
    namespace: pihole
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mini--traefik
  namespace: argocd
spec:
  project: mini
  source:
    repoURL: https://github.com/amanibhavam/deploy
    path: c/mini/traefik
    targetRevision: master
  destination:
    name: mini
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: imac--cilium
  namespace: argocd
spec:
  project: imac
  source:
    repoURL: https://github.com/amanibhavam/deploy
    path: c/imac/cilium
    targetRevision: master
  destination:
    name: imac
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: imac--kuma-zone
  namespace: argocd
spec:
  project: imac
  source:
    repoURL: https://github.com/amanibhavam/deploy
    path: c/imac/kuma-zone
    targetRevision: master
  destination:
    name: imac
    namespace: kuma-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: imac--argo-workflows
  namespace: argocd
spec:
  project: imac
  source:
    repoURL: https://github.com/amanibhavam/deploy
    path: c/imac/argo-workflows
    targetRevision: master
  destination:
    name: imac
    namespace: argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: imac--docker-registry
  namespace: argocd
spec:
  project: imac
  source:
    repoURL: https://github.com/amanibhavam/deploy
    path: c/imac/docker-registry
    targetRevision: master
  destination:
    name: imac
    namespace: docker-registry
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: imac--pihole
  namespace: argocd
spec:
  project: imac
  source:
    repoURL: https://github.com/amanibhavam/deploy
    path: c/imac/pihole
    targetRevision: master
  destination:
    name: imac
    namespace: pihole
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: imac--traefik
  namespace: argocd
spec:
  project: imac
  source:
    repoURL: https://github.com/amanibhavam/deploy
    path: c/imac/traefik
    targetRevision: master
  destination:
    name: imac
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mbpro--cilium
  namespace: argocd
spec:
  project: mbpro
  source:
    repoURL: https://github.com/amanibhavam/deploy
    path: c/mbpro/cilium
    targetRevision: master
  destination:
    name: mbpro
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mbpro--kuma-zone
  namespace: argocd
spec:
  project: mbpro
  source:
    repoURL: https://github.com/amanibhavam/deploy
    path: c/mbpro/kuma-zone
    targetRevision: master
  destination:
    name: mbpro
    namespace: kuma-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mbpro--argo-workflows
  namespace: argocd
spec:
  project: mbpro
  source:
    repoURL: https://github.com/amanibhavam/deploy
    path: c/mbpro/argo-workflows
    targetRevision: master
  destination:
    name: mbpro
    namespace: argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mbpro--docker-registry
  namespace: argocd
spec:
  project: mbpro
  source:
    repoURL: https://github.com/amanibhavam/deploy
    path: c/mbpro/docker-registry
    targetRevision: master
  destination:
    name: mbpro
    namespace: docker-registry
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mbpro--pihole
  namespace: argocd
spec:
  project: mbpro
  source:
    repoURL: https://github.com/amanibhavam/deploy
    path: c/mbpro/pihole
    targetRevision: master
  destination:
    name: mbpro
    namespace: pihole
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mbpro--traefik
  namespace: argocd
spec:
  project: mbpro
  source:
    repoURL: https://github.com/amanibhavam/deploy
    path: c/mbpro/traefik
    targetRevision: master
  destination:
    name: mbpro
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

